### ISSUE TITLE
뭔 사이드 프로젝트를 하셨나요?

### ISSUE THREAD

**Issue by rurumimic** [ghkdxofla/ghkdxofla.github.io#6]
<img src="https://media.giphy.com/media/KbH2G6237ZFQkyfxIH/giphy.gif">

없는데?

**Comment by rurumimic** [comment]
wtf auto-bot

![](https://upload.wikimedia.org/wikipedia/en/0/07/Autobot_small.jpg)

**Comment by ghkdxofla** [comment]
깃험 봇이 처리했으니 안심하라구!
